Tidying up
IQuOD/AutoQC pull request #265
Opened 2021-05-13 16:23 UTC by s-good

This pull request does some tidying in preparation for our production run:

- Remove warning message in AOML_spike.py due to using numpy.median on a masked array (the mask is already checked for missing data prior to the use of numpy.median so the warning message is not useful). Using numpy.ma.median prevents the warning being printed. Numpy.ma.mean was also used in place of numpy.mean, but I don't think this was giving warnings.
- Try to make all tests return a QC result for all levels. Some QC tests such as the track check were just returning a single value, which is inconsistent with what most of the tests are doing.
- Fix an issue that was occurring for the EN_std_level_bkg_and_buddy_check, which tries to use previously cached results from other tests. The code wasn't checking whether the result was present properly, causing the check to fail.
- Prevent a warning from the minmax test due to the presence of NaNs in the arrays. I have changed the code to check that the temperature, min and max are all present before attempting to make a QC decision and defaulting to a pass result if not.

2021-05-13 18:35 UTC, BillMills requested changes
Thanks for this, @s-good; I particularly like standardizing on per-level QC instead of jumping back and forth, that's much better.

See a couple of minor comments inline; I think the one in `EN_background_check` is the only one that really needs to change before we merge. My point about factorization in `constant_value` is a nice to have - should be easy to implement, but can live in a future PR.

2021-05-13 18:35 UTC, BillMills commented on qctests/EN_background_check.py
> +    #        return qc_log[0]
This likely isn't meant to be commented out - looks like that was done long ago (by me when porting from python 2->3, sorry) and forgotten about until now.

2021-05-13 18:35 UTC, BillMills commented on qctests/EN_constant_value_check.py
> +            return qc_log[0]
This block, from defining the query to deciding if something was successfully fetched from the DB, is both arcane enough and repeated enough to warrant its own helper function in utils, with a unit test or two. Doesn't have to block this PR, but would be a bit tidier.

2021-05-14 13:30 UTC, BillMills commented on util/dbutils.py
> +            print('QC results extracted from database:')
Looking great after today's updates, thanks @s-good - the only nit I'll pick (and we're really getting down to little stuff) is I'd remove the `print` statements from the successful path. These will result in thousands of lines in the logs that don't tell us much, and can drown out logs of actual problems. In future we should probably use different logging levels from the `logging` package, but that's beyond the scope of this PR.

The print statements in the error paths are good though - those are the things we want to stick out.

2021-05-14 14:45 UTC, BillMills commented
I love it - thanks for the amendments, I say merge it and start the production run!

2021-05-14 14:45 UTC, BillMills approved these changes

2021-05-14 14:48 UTC, s-good commented
Great! Thanks for the comments. I'll merge it now.

2021-05-14 14:48 UTC, merged